### PR TITLE
Use vppagent.MemifConnect and vppagent.Flush in vpp-icmp example

### PR DESCRIPTION
**Pull request by onobrod**
Issue: https://github.com/networkservicemesh/networkservicemesh/issues/1277

### CODE REVIEW

**Comment by nickolaev** [comment]
Actually with the invention of "universal-cnf": https://github.com/networkservicemesh/examples/pull/24 I wanted to completely remove the code that lives here.

**Comment by onobrod** [comment]
Ok, close the PR

**Comment by nickolaev** [comment]
@onobrod let's reconsider having this. maybe we can have both approaches in the same example. Please re-open it

**Comment by onobrod** [comment]
Seems I cannot reopen this even if I push the deleted branch again. Created a new one: https://github.com/networkservicemesh/examples/pull/32

**Pull request closed without merging**
