### PR TITLE
Added serviceAccount in bridge-domain manifests

### PR DESCRIPTION
**Pull request by uablrek**
This is required for insecure=false operation.

This PR only adds "serviceAccount: nsc-acc" (or "serviceAccount: nse-acc") in manifests. Without this clients get stuck in "Init" unless "insecure=true" is set.

### CODE REVIEW

**Comment by nickolaev** [comment]
OK while we are here can you please enable the CI tests for the bridge here:
https://github.com/networkservicemesh/examples/blob/master/.circleci/config.yml#L179

And then make sure they pass.

**Comment by uablrek** [comment]
The CI tests fails with the client stuck in "Init", which is exectly the problem this PR is supposed to fix.

But I can't see if the helm install uses "--set insecure=true", but if it doesn't I think the problem is that there are no "spire" pods running at all according to the test dump. Then the client *will* wait forever.

Please check if "--set insecure=true" is used and if not why there are no "spire" pods.

**Comment by uablrek** [comment]
Below is the pods on a succesful test in my environment. Note the "spire" pods;
```
> kubectl get pods -A
NAMESPACE     NAME                                    READY   STATUS    RESTARTS   AGE
default       bridge-domain-68bfbd576f-2w6qg          1/1     Running   0          50s
default       bridge-domain-ipv6-66bff4f4d5-srj7c     1/1     Running   0          33s
default       nsm-admission-webhook-c97f9bc9b-zsb9v   1/1     Running   0          102s
default       nsm-vpp-forwarder-5m26d                 1/1     Running   0          102s
default       nsm-vpp-forwarder-nl8rm                 1/1     Running   0          102s
default       nsm-vpp-forwarder-qljxg                 1/1     Running   0          102s
default       nsm-vpp-forwarder-wsqgz                 1/1     Running   0          102s
default       nsmgr-6klv2                             3/3     Running   0          100s
default       nsmgr-8n6s9                             3/3     Running   0          101s
default       nsmgr-t5ht7                             3/3     Running   0          100s
default       nsmgr-vzhp6                             3/3     Running   0          100s
default       prefix-service-79bcd7cb94-lm6kg         1/1     Running   0          102s
default       simple-client-78f8885659-d5d52          3/3     Running   0          46s
default       simple-client-78f8885659-ddnpx          3/3     Running   0          46s
default       simple-client-78f8885659-nl2nd          3/3     Running   0          46s
default       simple-client-ipv6-5fb98797cf-4brbl     3/3     Running   0          31s
default       simple-client-ipv6-5fb98797cf-jkdrv     3/3     Running   0          31s
default       simple-client-ipv6-5fb98797cf-jm9zd     3/3     Running   0          31s
kube-system   metrics-server-6dffbdcfb4-d9pmq         1/1     Running   0          2m16s
spire         spire-agent-6nkzq                       1/1     Running   0          102s
spire         spire-agent-jttvk                       1/1     Running   0          102s
spire         spire-agent-rbfjc                       1/1     Running   0          102s
spire         spire-agent-t6mnk                       1/1     Running   0          102s
spire         spire-server-0                          1/1     Running   0          101s
```

**Comment by nickolaev** [comment]
Example's CI currently runs with `insecure=true`, see here: https://github.com/networkservicemesh/examples/blob/master/.circleci/config.yml#L140

**Comment by nickolaev** [comment]
Are you using `kind`, `vagrant` or jsut plain k8s?

**Comment by uablrek** [comment]
Plain k8s.

**Comment by uablrek** [comment]
I will try with insecure and disable spire and verify that it works. (but maybe tomorrow)

**Pull request merged**
