### PR TITLE
Add a load-balancer example

### PR DESCRIPTION
**Pull request by uablrek**
## A VPP load-balancer example with access from external machines

Original branch view;
https://github.com/Nordix/examples/tree/load-balancer/examples/load-balancer

### CODE REVIEW

**Review by nickolaev — COMMENTED** [review]
Looks interesting. I guess that the "proper" way to interface with the vppagent is to have a dedicate LB plugin here:
https://github.com/ligato/vpp-agent/tree/master/plugins/vpp

**Comment by uablrek** [comment]
@nickolaev 

Is there any example of the "proper" way to bring in external traffic from the real world. The existing example seems to connect vpp-vpp only. I was hoping a lot for some hint in the "gw-routers" example but found only this;
```
      - command:
          name: "echo"
          args: ["Do attach the PCI device here and assign it an IP address from 10.60.0.0/24"]

```
which does not help much.

**Comment by nickolaev** [comment]
You should check how the CNF Testbed applies the example on the bare-metal:

https://github.com/cncf/cnf-testbed/tree/master/examples/use_case/gw-routers-on-k8s-nsm-on-packet

**Comment by nickolaev** [comment]
Please cleanup you changes in `.circleci/config.yml`. Now tests are called automatically.

**Comment by nickolaev** [comment]
@uablrek, please merge or rebase to master. No changes in the `.circleci/config.yml` are needed. All tests will run out of the box.

**Comment by uablrek** [comment]
@nickolaev Done

**Review by nickolaev — APPROVED** [review]
@uablrek I will merge it as it is. Then will try to debug why it is failing. If I find something wrong I will create and issue and assign it to you.
Looks a great job. Thanks!

**Pull request merged**
